window.ZOONELIBRE_PRODUCTS = [
  {
    "id": "fado-white",
    "name": "IKEA FADO Table Lamp",
    "variant": "White · 10 in",
    "brand": "IKEA",
    "price": 29.99,
    "compare": null,
    "category": "Ambient",
    "color": "White",
    "type": "Globe",
    "desc": "Round white glass table lamp designed for soft, cozy mood lighting.",
    "url": "https://www.ikea.com/us/en/p/fado-table-lamp-white-70096377/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/fado-table-lamp-white-70096377/"
  },
  {
    "id": "fado-pink",
    "name": "IKEA FADO Table Lamp",
    "variant": "Pink Glass · 10 in",
    "brand": "IKEA",
    "price": 29.99,
    "compare": null,
    "category": "Ambient",
    "color": "Pink",
    "type": "Globe",
    "desc": "Pink glass version of the FADO globe lamp for warm decorative lighting.",
    "url": "https://www.ikea.com/us/en/p/fado-table-lamp-pink-glass-00592634/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/fado-table-lamp-pink-glass-00592634/"
  },
  {
    "id": "varmblixt-orange",
    "name": "IKEA VARMBLIXT LED Lamp",
    "variant": "Orange Glass · Round · 12 in",
    "brand": "IKEA",
    "price": 89.99,
    "compare": null,
    "category": "Decorative",
    "color": "Orange",
    "type": "Table / Wall",
    "desc": "Iconic orange glass LED lamp with a sculptural donut shape and warm glow.",
    "url": "https://www.ikea.com/us/en/p/varmblixt-led-table-wall-lamp-orange-glass-round-90525150/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/varmblixt-led-table-wall-lamp-orange-glass-round-90525150/"
  },
  {
    "id": "dejsa",
    "name": "IKEA DEJSA Table Lamp",
    "variant": "Beige / Opal Glass · 11 in",
    "brand": "IKEA",
    "price": 89.99,
    "compare": null,
    "category": "Bedside",
    "color": "Beige",
    "type": "Glass",
    "desc": "Mouth-blown opal glass lamp with chrome details and soft diffused light.",
    "url": "https://www.ikea.com/us/en/p/dejsa-table-lamp-beige-opal-glass-00404987/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/dejsa-table-lamp-beige-opal-glass-00404987/"
  },
  {
    "id": "tokabo",
    "name": "IKEA TOKABO Table Lamp",
    "variant": "Opal Glass",
    "brand": "IKEA",
    "price": 19.99,
    "compare": null,
    "category": "Bedside",
    "color": "White",
    "type": "Mini",
    "desc": "Compact opal glass lamp that fits small shelves and nightstands.",
    "url": "https://www.ikea.com/us/en/p/tokabo-table-lamp-glass-opal-80358019/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/tokabo-table-lamp-glass-opal-80358019/"
  },
  {
    "id": "tvaerhand",
    "name": "IKEA TVÄRHAND Table Lamp",
    "variant": "Black / Bamboo",
    "brand": "IKEA",
    "price": 24.99,
    "compare": null,
    "category": "Decorative",
    "color": "Black",
    "type": "Exposed Bulb",
    "desc": "Minimal curved black metal lamp with a natural bamboo base.",
    "url": "https://www.ikea.com/us/en/p/tvaerhand-table-lamp-black-bamboo-60518410/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/tvaerhand-table-lamp-black-bamboo-60518410/"
  },
  {
    "id": "fado-smart",
    "name": "IKEA FADO / KAJPLATS Smart Lamp",
    "variant": "Color + White Spectrum",
    "brand": "IKEA",
    "price": 44.98,
    "compare": null,
    "category": "Smart",
    "color": "Multicolor",
    "type": "Smart Globe",
    "desc": "FADO globe lamp bundled with a smart color and white-spectrum bulb and remote.",
    "url": "https://www.ikea.com/us/en/p/fado-kajplats-table-lamp-with-led-bulb-smart-color-and-white-spectrum-s29654971/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/fado-kajplats-table-lamp-with-led-bulb-smart-color-and-white-spectrum-s29654971/"
  },
  {
    "id": "spetsboj",
    "name": "IKEA SPETSBOJ Table Lamp",
    "variant": "Dimmable White · 9 in",
    "brand": "IKEA",
    "price": 19.99,
    "compare": null,
    "category": "Bedside",
    "color": "White",
    "type": "Dimmable",
    "desc": "Compact metal table lamp with a rotating shade for simple dimming.",
    "url": "https://www.ikea.com/us/en/p/spetsboj-table-lamp-dimmable-white-70589119/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/spetsboj-table-lamp-dimmable-white-70589119/"
  },
  {
    "id": "tarnaby",
    "name": "IKEA TÄRNABY Table Lamp",
    "variant": "Dimmable Anthracite · 10 in",
    "brand": "IKEA",
    "price": 34.99,
    "compare": null,
    "category": "Vintage",
    "color": "Anthracite",
    "type": "Dimmable",
    "desc": "Kerosene-lamp-inspired bedside light with a built-in dimmer knob.",
    "url": "https://www.ikea.com/us/en/p/taernaby-table-lamp-dimmable-anthracite-00323887/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/taernaby-table-lamp-dimmable-anthracite-00323887/"
  },
  {
    "id": "grono",
    "name": "IKEA GRÖNÖ Table Lamp",
    "variant": "Frosted Glass White · 9 in",
    "brand": "IKEA",
    "price": 12.99,
    "compare": null,
    "category": "Bedside",
    "color": "White",
    "type": "Frosted Glass",
    "desc": "Simple frosted-glass lamp that spreads soft, warm mood lighting.",
    "url": "https://www.ikea.com/us/en/p/groenoe-table-lamp-frosted-glass-white-10373221/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/groenoe-table-lamp-frosted-glass-white-10373221/"
  },
  {
    "id": "solklint",
    "name": "IKEA SOLKLINT Table Lamp",
    "variant": "Brass / Gray Clear Glass · 11 in",
    "brand": "IKEA",
    "price": 29.99,
    "compare": null,
    "category": "Decorative",
    "color": "Brass",
    "type": "Glass",
    "desc": "Brass-look lamp with patterned gray clear glass that casts decorative shadows.",
    "url": "https://www.ikea.com/us/en/p/solklint-table-lamp-brass-gray-clear-glass-10464283/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/solklint-table-lamp-brass-gray-clear-glass-10464283/"
  },
  {
    "id": "blasverk",
    "name": "IKEA BLÅSVERK Table Lamp",
    "variant": "Beige · 14 in",
    "brand": "IKEA",
    "price": 19.99,
    "compare": null,
    "category": "Modern",
    "color": "Beige",
    "type": "Table Lamp",
    "desc": "Rounded modern table lamp with a soft, understated beige finish.",
    "url": "https://www.ikea.com/us/en/p/blasverk-table-lamp-beige-80520935/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/blasverk-table-lamp-beige-80520935/"
  },
  {
    "id": "arstid",
    "name": "IKEA ÅRSTID Table Lamp",
    "variant": "Brass / White",
    "brand": "IKEA",
    "price": 39.99,
    "compare": null,
    "category": "Classic",
    "color": "Brass",
    "type": "Fabric Shade",
    "desc": "Timeless brass-tone lamp with a white fabric shade and pull switch.",
    "url": "https://www.ikea.com/us/en/p/arstid-table-lamp-brass-white-80321380/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/arstid-table-lamp-brass-white-80321380/"
  },
  {
    "id": "simrishamn",
    "name": "IKEA SIMRISHAMN Table Lamp",
    "variant": "Chrome / Opal Glass · 17 in",
    "brand": "IKEA",
    "price": 99.99,
    "compare": null,
    "category": "Modern",
    "color": "Chrome",
    "type": "Double Globe",
    "desc": "Statement lamp combining polished chrome with two opal-glass globes.",
    "url": "https://www.ikea.com/us/en/p/simrishamn-table-lamp-chrome-plated-opal-glass-40437684/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/simrishamn-table-lamp-chrome-plated-opal-glass-40437684/"
  },
  {
    "id": "kuddlava",
    "name": "IKEA KUDDLAVA Table Lamp",
    "variant": "Pleated White · 11 in",
    "brand": "IKEA",
    "price": 19.99,
    "compare": null,
    "category": "Scandinavian",
    "color": "White",
    "type": "Pleated",
    "desc": "Pleated Scandinavian-inspired shade with a decorative solid-wood knob.",
    "url": "https://www.ikea.com/us/en/p/kuddlava-table-lamp-pleated-white-10601204/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/kuddlava-table-lamp-pleated-white-10601204/"
  },
  {
    "id": "avhall",
    "name": "IKEA AVHÅLL LED Portable Lamp",
    "variant": "Nickel Plated · Outdoor · 11½ in",
    "brand": "IKEA",
    "price": 29.99,
    "compare": null,
    "category": "Portable",
    "color": "Silver",
    "type": "Battery",
    "desc": "Battery-operated dimmable metal lamp designed for flexible indoor and outdoor use.",
    "url": "https://www.ikea.com/us/en/p/avhall-led-portable-lamp-battery-operated-dimmable-nickel-plated-outdoor-50614148/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/avhall-led-portable-lamp-battery-operated-dimmable-nickel-plated-outdoor-50614148/"
  },
  {
    "id": "barlast",
    "name": "IKEA BARLAST Table Lamp",
    "variant": "Black / White · 12 in",
    "brand": "IKEA",
    "price": 5.99,
    "compare": null,
    "category": "Budget",
    "color": "Black",
    "type": "Table Lamp",
    "desc": "Straightforward black-and-white bedside lamp with a lightweight compact design.",
    "url": "https://www.ikea.com/us/en/p/barlast-table-lamp-black-white-90504567/",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.ikea.com/us/en/p/barlast-table-lamp-black-white-90504567/"
  },
  {
    "id": "govee-2s",
    "name": "Govee RGBIC Smart Table Lamp 2S",
    "variant": "Multicolor",
    "brand": "Govee",
    "price": 59.99,
    "compare": 69.99,
    "category": "Smart",
    "color": "Multicolor",
    "type": "RGBIC",
    "desc": "Smart RGBIC table lamp with app control, dynamic scenes and colorful ambient lighting.",
    "url": "https://www.bestbuy.com/product/govee-rgbic-smart-table-lamp-2s-multi/J3R84LT5JZ/sku/6624249",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.bestbuy.com/product/govee-rgbic-smart-table-lamp-2s-multi/J3R84LT5JZ/sku/6624249"
  },
  {
    "id": "hue-go",
    "name": "Philips Hue Go Bluetooth Table Lamp",
    "variant": "White + Color Ambiance",
    "brand": "Philips Hue",
    "price": 95.99,
    "compare": 98.99,
    "category": "Smart",
    "color": "Multicolor",
    "type": "Portable Smart",
    "desc": "Portable smart mood lamp with Bluetooth and white-and-color ambiance lighting.",
    "url": "https://www.bestbuy.com/product/philips-hue-go-bluetooth-table-lamp-white-and-color-ambiance/J7GHXZXYQ7/sku/6367453",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.bestbuy.com/product/philips-hue-go-bluetooth-table-lamp-white-and-color-ambiance/J7GHXZXYQ7/sku/6367453"
  },
  {
    "id": "govee-pro",
    "name": "Govee Smart Table Lamp 2 Pro",
    "variant": "Sound by JBL · Multicolor",
    "brand": "Govee",
    "price": 159.99,
    "compare": 179.99,
    "category": "Smart",
    "color": "Multicolor",
    "type": "Light + Speaker",
    "desc": "Premium smart lamp with customizable LEDs, music-light sync and integrated JBL sound.",
    "url": "https://www.bestbuy.com/product/govee-smart-table-lamp-2-pro-sound-by-jbl-multi/J3R84LT5WQ/sku/6636530",
    "image": "https://image.thum.io/get/width/900/crop/900/noanimate/https://www.bestbuy.com/product/govee-smart-table-lamp-2-pro-sound-by-jbl-multi/J3R84LT5WQ/sku/6636530"
  }
];